// Shared, design-system-level components. Import from here rather than deep paths.
export { Icon, type IconName } from './icons/Icon'
export { Badge, type BadgeTone, type BadgeVariant } from './ui/Badge'
export { Button, type ButtonVariant } from './ui/Button'
export { buttonClassName } from './ui/buttonClassName'
export { Card, CardBody, CardHeader, CARD_SURFACE } from './ui/Card'
export { DataTable, type DataTableColumn, type DataTableSortDirection } from './ui/DataTable'
export { DatePicker, MonthPicker } from './ui/DatePicker'
export { DateRangePicker } from './ui/DateRangePicker'
export { EmptyState } from './ui/EmptyState'
export { ErrorState } from './ui/ErrorState'
export { Input } from './ui/Input'
export { ListRow, RowList } from './ui/ListRow'
export { ListItemLink } from './ui/ListItemLink'
export { Modal } from './ui/Modal'
export { SegmentedControl, type SegmentOption } from './ui/SegmentedControl'
export { Skeleton } from './ui/Skeleton'
export { StatCard, StatCardSkeleton, type StatTone, type StatTrend } from './ui/StatCard'
export { TitleLink } from './ui/TitleLink'
export { StatusBadge, type StatusDefinition, type StatusMap } from './ui/StatusBadge'
export { followUpDueMap, followUpStatusMap, type FollowUpDueState } from './status/followUp'
export { frequentVisitorMap } from './status/frequentVisitor'
export { inventoryFlagMap, type InventoryFlag } from './status/inventory'
export { ListCard, ListCardSkeleton } from './ui/ListCard'
export { Select, type SelectOption } from './ui/Select'
export { MultiSelect, type MultiSelectOption } from './ui/MultiSelect'
export { Pagination } from './ui/Pagination'
export { Textarea } from './ui/Textarea'
export {
  FollowUpPrompt,
  validateFollowUp,
  type FollowUpDraft,
  type FollowUpErrors,
} from './forms/FollowUpPrompt'
export { StudentNumberField } from './forms/StudentNumberField'
export { InventoryItemPicker, type PickableItem } from './forms/InventoryItemPicker'
export { ItemsGivenField, INSTRUCTIONS_MAX, type ItemLineDraft } from './forms/ItemsGivenField'
