import { useState } from 'react'
import { Link } from 'react-router'
import { Card, CardBody, CardHeader, EmptyState, ErrorState, Icon, buttonClassName } from '../../../components'
import type { SessionUser } from '../../../lib/mock-db'
import type { StudentNumber } from '../../../types/entities'
import { paths } from '../../../routes/paths'
import { lookupStudentByNumber, type QrLookupResult } from '../api/qrLookupApi'
import { QrScannerView } from '../shared/QrScannerView'

function DesktopResult({ result }: { result: QrLookupResult }) {
  const { student } = result
  return <div className="flex flex-col gap-4"><Card aria-labelledby="desktop-student-title"><CardHeader titleId="desktop-student-title" title={student.fullName} description={`${student.studentNumber} · ${student.gradeLevel}`} icon={<Icon name="users" />} /><CardBody className="grid gap-4 md:grid-cols-3"><div><p className="text-xs font-semibold text-text-secondary">Allergies</p><p className="text-sm text-text-primary">{student.allergies.length ? student.allergies.join(', ') : 'None recorded'}</p></div><div><p className="text-xs font-semibold text-text-secondary">Conditions</p><p className="text-sm text-text-primary">{student.medicalConditions.length ? student.medicalConditions.join(', ') : 'None recorded'}</p></div><div><p className="text-xs font-semibold text-text-secondary">Emergency contact</p><p className="text-sm text-text-primary">{student.emergencyContact?.name ?? 'None recorded'}</p></div></CardBody></Card><Card aria-labelledby="desktop-actions-title"><CardHeader titleId="desktop-actions-title" title="Student quick-actions" description="Continue with the identified student already attached." icon={<Icon name="layoutGrid" />} /><CardBody className="grid gap-3 md:grid-cols-2"><Link className={buttonClassName({ variant: 'secondary' })} to={paths.visitNew(student.studentNumber)}><Icon name="stethoscope" />Record Visit</Link><Link className="inline-flex min-h-10 cursor-pointer items-center justify-center gap-2 rounded-md border border-warning bg-warning px-4 text-sm font-semibold text-white transition-[filter] hover:brightness-90" to={paths.incidentNew(student.studentNumber)}><Icon name="alertTriangle" />Log Emergency</Link><Link className={buttonClassName({ variant: 'secondary' })} to={paths.studentProfile(student.studentNumber)}><Icon name="users" />View Full Profile</Link><Link className={buttonClassName({ variant: 'secondary' })} to={paths.inventoryDispense(student.studentNumber)}><Icon name="package" />Dispense Medicine</Link><Link className={buttonClassName({ variant: 'secondary' })} to={paths.peReferral(student.studentNumber)}><Icon name="activity" />PE/Sports Referral</Link></CardBody></Card></div>
}

export function QrDesktopHubPage({ viewer }: { viewer: SessionUser }) {
  const [result, setResult] = useState<QrLookupResult | null>(null)
  const [error, setError] = useState('')
  async function lookup(studentNumber: StudentNumber) { setError(''); setResult(null); try { setResult(await lookupStudentByNumber(studentNumber, viewer)) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to complete lookup.') } }
  return <div className="mx-auto flex max-w-page-narrow flex-col gap-4 px-4 pt-10 pb-8 sm:px-8"><header><h1 className="text-2xl font-bold tracking-tight text-text-primary">QR Scan / Lookup</h1><p className="mt-1 text-sm text-text-secondary">Identify one student from the Staff workstation, then continue to a pre-filled action.</p></header><QrScannerView title="Identify student" description="Scan with a webcam or enter the Student Number manually." onDetected={lookup} onScanStart={() => setError('')} />{error && <ErrorState title={error === 'Student not found' ? 'Student not found.' : 'Unable to complete lookup.'} description="Check the Student Number and try again." />}{result ? <DesktopResult result={result} /> : !error && <EmptyState icon="qrCode" title="Ready to identify a student" description="Scan a QR code or enter a Student Number to see the student's available actions." />}</div>
}
