import { getMonthlyReport, type MonthlyReportData } from '../../../lib/mock-db'

/**
 * Reports (#19–#21). Every figure is generated by the data layer from raw records for the chosen
 * month (visit/incident/follow-up counts, the incident archive, visits per complaint), so a report
 * always matches the list screens it summarizes. `month` is "YYYY-MM".
 */
export type { MonthlyReportData }

export function fetchMonthlyReport(month: string): Promise<MonthlyReportData> {
  return getMonthlyReport(month)
}
