// Shared, design-system-level components. Import from here rather than deep paths.
export { Icon, type IconName } from './icons/Icon'
export { Badge, type BadgeTone, type BadgeVariant } from './ui/Badge'
export { Button, type ButtonVariant } from './ui/Button'
export { Card, CardBody, CardHeader, CARD_SURFACE } from './ui/Card'
export { DataTable, type DataTableColumn } from './ui/DataTable'
export { DateRangePicker } from './ui/DateRangePicker'
export { EmptyState } from './ui/EmptyState'
export { ErrorState } from './ui/ErrorState'
export { Input } from './ui/Input'
export { ListRow, RowList } from './ui/ListRow'
export { SegmentedControl, type SegmentOption } from './ui/SegmentedControl'
export { Skeleton } from './ui/Skeleton'
export { StatCard, StatCardSkeleton, type StatTone, type StatTrend } from './ui/StatCard'
export { StatusBadge, type StatusDefinition, type StatusMap } from './ui/StatusBadge'
export { followUpDueMap, followUpStatusMap, type FollowUpDueState } from './status/followUp'
export { frequentVisitorMap } from './status/frequentVisitor'
export { inventoryFlagMap, type InventoryFlag } from './status/inventory'
export { ListCard, ListCardSkeleton } from './ui/ListCard'
